name: Check dist

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Setup Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: 1.23.2

      - uses: pulumi/actions@v6

      - name: Pulumi login
        run: |
          pulumi login --local
      
      - name: Romeo environment
        id: romeo
        uses: pandatix/romeo-action@main
        with:
          kubeconfig: toto
        env:
          PULUMI_CONFIG_PASSPHRASE: ""

      - name: Outputs
        run: |
          echo "port: ${{ steps.romeo.outputs.port }}"
          echo "claimName: ${{ steps.romeo.outputs.claim-name }}"
