name: Check dist

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Romeo environment
        uses: pandatix/romeo-action@2b3b826935a61255cf1ccdac3f86321f81ae8fe2
